# -*- coding: utf-8 -*-
"""YOLO8.ipynb

Automatically generated by Colab.


"""

!pip install roboflow

pip install ultralytics

from roboflow import Roboflow
rf = Roboflow(api_key="key")
project = rf.workspace("myworkspace-gcdng").project("furniture-detection-dg1lo")
version = project.version(2)
dataset = version.download("yolov8")

"""Для оубчения моделей из библиотеки ultralytics сначала необходимо подготовить конфигурационный файл, если набор данных скачан из Roboflow, он сгенерирован автоматически и пригалается к набору данных."""

!cat Furniture-Detection-2/data.yaml

"""Для корректного запуска обучения необходимо поправить пути до директорий с изображениями, так как скрипт обучения YOLO будет искать полные пути до директорий с изображениями и разметкой."""

import pathlib
import yaml

def delete_first_folder(p: str) -> str:
  return str(pathlib.Path(*pathlib.Path(p).parts[1:]))

def add_root_path(p: str) -> str:
  return '/content/' + p

with open('Furniture-Detection-2/data.yaml', 'r') as f:
  data = yaml.safe_load(f)

data['train'] = add_root_path('Furniture-Detection-2/' + delete_first_folder(data['train']))
data['val'] = add_root_path('Furniture-Detection-2/' + delete_first_folder(data['val']))
data['test'] = add_root_path('Furniture-Detection-2/' + delete_first_folder(data['test']))

with open('Furniture-Detection-2/fixed_data.yaml', 'w') as f:
  yaml.safe_dump(data, f)

data

"""# Новый раздел

Теперь можно запустить обучение YOLO, для обучение берётся самая легковесная архитектура YOLO-Nano.
"""

# Обучение модели Nano на 20 эпохах с размером входного изображения 480 пикселей
!yolo detect train model=yolov8n.pt data="Furniture-Detection-2/fixed_data.yaml" epochs=20 imgsz=640 device=0

import glob, os

runs = sorted(glob.glob("runs/detect/train*"), key=os.path.getmtime)
best = runs[-1] + "/weights/best.pt"

!yolo detect predict model="$best" source="Furniture-Detection-2/test/images" \
  save=True conf=0.25 device=0 project="runs/predict_test" name="best" exist_ok=True

from google.colab import files
files.download('/content/predict_results.zip')

from ultralytics import YOLO

# загрузить обученную модель
model = YOLO("runs/detect/train/weights/best.pt")

# экспорт в TFLite
model.export(format="tflite", nms=True, conf=0.25, iou=0.45, topk=100, imgsz=640)

import yaml
yaml_path = "Furniture-Detection-2/data.yaml"

# куда сохранить labels.txt
output_path = "labels.txt"

# загрузка yaml
with open(yaml_path, "r") as f:
    data = yaml.safe_load(f)

# извлекаем список классов
labels = data["names"]

# записываем в файл
with open(output_path, "w") as f:
    for label in labels:
        f.write(label + "\n")



